import CryptoKit
import Foundation
import Testing
@testable import ProviderCore

// MARK: - Cross-Language NaCl Box Tests (Golden Vectors from Go)

// These vectors were generated by Go's golang.org/x/crypto/nacl/box with fixed keys and nonce.
// If any of these tests fail, the Swift NaCl implementation is NOT wire-compatible with Go/Rust.

private let goldenProviderPrivateKeyHex = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
private let goldenEphemeralPublicKeyB64 = "rUOL+uMfbAk9YdQzklXqeYCSyfrdB7l4J/Swrp3ufBw="

struct GoldenVector: Sendable {
    let name: String
    let ciphertextB64: String
    let plaintext: String
}

private let goldenVectors: [GoldenVector] = [
    GoldenVector(
        name: "hello",
        ciphertextB64: "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXZGqVtM7CzvUzjuv8z5nMD2Sk+g7RhuEOvfk2Xns=",
        plaintext: "hello from Go"
    ),
    GoldenVector(
        name: "json",
        ciphertextB64: "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXBEh64PeX5/KPPTPaFAFkJHfj+w3aw+te6LZifGcJdS8d1/aSifvDne+pw2W4tRO2Hz6Nz8AbtNRurlE6LxNKPV+I/OEjMotRwpxKHQ==",
        plaintext: #"{"model":"test","messages":[{"role":"user","content":"hi"}]}"#
    ),
    GoldenVector(
        name: "empty",
        ciphertextB64: "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGd5WgKY2kgufhPrGUBWGig==",
        plaintext: ""
    ),
    GoldenVector(
        name: "unicode",
        ciphertextB64: "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXsrGyAb1PhMJKM/jWGp9d2O9ABYE8NWT9eXeXuPf8+OeHLHR0drpUZxAG",
        plaintext: "こんにちは世界 🌍"
    ),
]

@Test("NaCl box: decrypt Go-generated golden vectors", arguments: goldenVectors)
func naclBoxDecryptsGoGoldenVector(_ vector: GoldenVector) throws {
    let providerPriv = try Data(hexString: goldenProviderPrivateKeyHex)
    let keyPair = try NodeKeyPair(rawSecret: providerPriv)

    let ephPubData = Data(base64Encoded: goldenEphemeralPublicKeyB64)!
    let ciphertext = Data(base64Encoded: vector.ciphertextB64)!

    let decrypted = try keyPair.decrypt(senderPublicKey: ephPubData, ciphertext: ciphertext)
    let decryptedString = String(data: decrypted, encoding: .utf8)!

    #expect(decryptedString == vector.plaintext,
            "Vector '\(vector.name)': expected \(vector.plaintext), got \(decryptedString)")
}

@Test("NaCl box: decrypt Go-generated reverse direction vector")
func naclBoxDecryptsGoReverseVector() throws {
    let ephPriv = try Data(hexString: "a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0")
    let keyPair = try NodeKeyPair(rawSecret: ephPriv)

    let senderPubB64 = "B6N8vBQgk8i3VdwbEOhstCY3StFqqFPtC9/AsrhtHHw="
    let ciphertextB64 = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXnPRmM91+Fsv168WzsGr0SH6k5RLRyPQZ8vJkdnldJ3FQzPqFn+g="

    let senderPub = Data(base64Encoded: senderPubB64)!
    let ciphertext = Data(base64Encoded: ciphertextB64)!

    let decrypted = try keyPair.decrypt(senderPublicKey: senderPub, ciphertext: ciphertext)
    let decryptedString = String(data: decrypted, encoding: .utf8)!

    #expect(decryptedString == "response from provider")
}

@Test("NaCl box: Swift encrypt → Swift decrypt round-trip")
func naclBoxSwiftRoundTrip() throws {
    let alice = NodeKeyPair.generate()
    let bob = NodeKeyPair.generate()

    let plaintext = Data("cross-language round-trip test payload".utf8)
    let encrypted = try alice.encrypt(recipientPublicKey: bob.publicKeyBytes, plaintext: plaintext)
    let decrypted = try bob.decrypt(senderPublicKey: alice.publicKeyBytes, ciphertext: encrypted)

    #expect(decrypted == plaintext)
}

@Test("NaCl box: EncryptedPayload wire format round-trip")
func naclBoxPayloadRoundTrip() throws {
    let provider = NodeKeyPair.generate()
    let coordinator = NodeKeyPair.generate()

    let message = Data(#"{"model":"qwen","messages":[{"role":"user","content":"test"}]}"#.utf8)

    let payload = try coordinator.encryptPayload(recipientPublicKey: provider.publicKeyBytes, plaintext: message)

    #expect(!payload.ephemeralPublicKey.isEmpty)
    #expect(!payload.ciphertext.isEmpty)

    let decrypted = try provider.decryptPayload(payload)
    #expect(decrypted == message)
}

@Test("NaCl box: tampered ciphertext fails authentication")
func naclBoxRejectsTamperedCiphertext() throws {
    let alice = NodeKeyPair.generate()
    let bob = NodeKeyPair.generate()

    let plaintext = Data("sensitive data".utf8)
    var encrypted = try alice.encrypt(recipientPublicKey: bob.publicKeyBytes, plaintext: plaintext)

    // Flip a byte in the ciphertext (after the 24-byte nonce)
    encrypted[encrypted.count - 1] ^= 0xFF

    #expect(throws: CryptoError.self) {
        _ = try bob.decrypt(senderPublicKey: alice.publicKeyBytes, ciphertext: encrypted)
    }
}

@Test("NaCl box: wrong key fails decryption")
func naclBoxRejectsWrongKey() throws {
    let alice = NodeKeyPair.generate()
    let bob = NodeKeyPair.generate()
    let eve = NodeKeyPair.generate()

    let plaintext = Data("for bob only".utf8)
    let encrypted = try alice.encrypt(recipientPublicKey: bob.publicKeyBytes, plaintext: plaintext)

    #expect(throws: CryptoError.self) {
        _ = try eve.decrypt(senderPublicKey: alice.publicKeyBytes, ciphertext: encrypted)
    }
}

// MARK: - Hex helper

extension Data {
    init(hexString: String) throws {
        var data = Data()
        var hex = hexString
        while !hex.isEmpty {
            let byte = hex.prefix(2)
            hex = String(hex.dropFirst(2))
            guard let b = UInt8(byte, radix: 16) else {
                throw CryptoError.decryptionFailed
            }
            data.append(b)
        }
        self = data
    }
}

// MARK: - X25519ChaChaPoly Tests

@Test func x25519ChaChaPolyRoundTripsWithDeterministicInputs() throws {
    let recipient = try X25519KeyAgreementKeyPair(rawPrivateKey: Data(repeating: 7, count: 32))
    let sender = try X25519KeyAgreementKeyPair(rawPrivateKey: Data(repeating: 9, count: 32))
    let cipher = X25519ChaChaPoly(
        salt: Data("test-salt".utf8),
        sharedInfo: Data("test-info".utf8)
    )
    let plaintext = Data("single request foundation".utf8)
    let aad = Data("req-123".utf8)
    let nonce = Data(0..<12)

    let sealed = try cipher.seal(
        plaintext: plaintext,
        recipientPublicKey: recipient.publicKey,
        senderKeyPair: sender,
        nonce: nonce,
        authenticatedData: aad
    )
    let opened = try cipher.open(sealed, recipientKeyPair: recipient, authenticatedData: aad)

    #expect(sealed.senderPublicKey == sender.publicKey)
    #expect(sealed.nonce == nonce)
    #expect(sealed.combinedCiphertext.count == nonce.count + sealed.ciphertext.count + sealed.tag.count)
    #expect(opened == plaintext)
}

@Test func x25519ChaChaPolyRejectsTamperedAuthenticatedData() throws {
    let recipient = try X25519KeyAgreementKeyPair(rawPrivateKey: Data(repeating: 1, count: 32))
    let sender = try X25519KeyAgreementKeyPair(rawPrivateKey: Data(repeating: 2, count: 32))
    let cipher = X25519ChaChaPoly()
    let sealed = try cipher.seal(
        plaintext: Data("hello".utf8),
        recipientPublicKey: recipient.publicKey,
        senderKeyPair: sender,
        nonce: Data(repeating: 3, count: 12),
        authenticatedData: Data("req-good".utf8)
    )

    #expect(throws: CryptoKitError.self) {
        _ = try cipher.open(
            sealed,
            recipientKeyPair: recipient,
            authenticatedData: Data("req-bad".utf8)
        )
    }
}

@Test func x25519ChaChaPolyValidatesKeyAndNonceLengths() throws {
    #expect(throws: X25519ChaChaPolyError.invalidPrivateKeyLength(31)) {
        _ = try X25519KeyAgreementKeyPair(rawPrivateKey: Data(repeating: 0, count: 31))
    }

    let recipient = try X25519KeyAgreementKeyPair(rawPrivateKey: Data(repeating: 5, count: 32))
    let cipher = X25519ChaChaPoly()

    #expect(throws: X25519ChaChaPolyError.invalidPublicKeyLength(31)) {
        _ = try cipher.seal(
            plaintext: Data(),
            recipientPublicKey: Data(repeating: 1, count: 31),
            nonce: Data(repeating: 0, count: 12)
        )
    }

    #expect(throws: X25519ChaChaPolyError.invalidNonceLength(11)) {
        _ = try cipher.seal(
            plaintext: Data(),
            recipientPublicKey: recipient.publicKey,
            nonce: Data(repeating: 0, count: 11)
        )
    }
}
